const CACHE='adaptive-exam-v1.2.5-performance-20261006';
const CAMBRIDGE_IMAGES=Array.from({length:10},(_,i)=>Array.from({length:4},(_,j)=>`./assets/cambridge/exam-${String(i+1).padStart(2,'0')}-part-${j+1}.webp`)).flat();
const ASSETS=['./','./index.html','./app.js','./performance-adapter.js','./data/cambridge-bank.js','./data/engexam-bank.js','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png','/adrian-core/design/adrian-visual-system.js','/adrian-core/components/adrian-achievements.js','/adrian-core/components/adrian-performance.js','/adrian-core/components/hub-path-game.js','./adaptive-language-dashboard.js',...CAMBRIDGE_IMAGES];
const CORE_RE=/\.(?:html|js|css|json|webmanifest)$/i;
function withTimeout(req,ms,init={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return fetch(req,{...init,signal:c.signal}).finally(()=>clearTimeout(t));}
async function installCore(){const c=await caches.open(CACHE);try{await Promise.all(ASSETS.map(async url=>{const req=new Request(new URL(url,self.registration.scope),{cache:'reload'}),r=await withTimeout(req,10000,{cache:'reload'});if(!r||!r.ok)throw Error(`Core asset failed: ${url}`);await c.put(req,r.clone());}));}catch(e){await caches.delete(CACHE);throw e;}}
self.addEventListener('install',e=>e.waitUntil(installCore().then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('adaptive-exam-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function network(req,ms=3500){try{return await withTimeout(req,ms,{cache:'no-cache'});}catch(_){return null;}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;e.respondWith((async()=>{const c=await caches.open(CACHE),core=e.request.mode==='navigate'||CORE_RE.test(u.pathname);if(core){const r=await network(e.request,1800);if(r&&r.ok){await c.put(e.request,r.clone());return r;}const hit=await c.match(e.request,{ignoreSearch:true});if(hit)return hit;if(e.request.mode==='navigate')return (await c.match('./index.html'))||(await c.match('./'))||Response.error();return Response.error();}const hit=await c.match(e.request,{ignoreSearch:true});if(hit)return hit;const r=await network(e.request,5000);if(r&&r.ok){await c.put(e.request,r.clone());return r;}return Response.error();})());});
